version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.1

jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Google Cloud SDK (gcloud CLI)
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk

      - run:
          name: Authenticate Docker to GCP Artifact Registry
          command: |
            echo "$GCLOUD_SERVICE_KEY" > ${HOME}/gcloud-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - run:
          name: Build Docker image
          command: |
            docker build -t us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REPO/app:latest .

      - run:
          name: Push Docker image to GCP Artifact Registry
          command: |
            docker push us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REPO/app:latest

  continuous-delivery:
    machine:
      image: ubuntu-2204:current
      resource_class: medium
    steps:
      - run:
          name: Authenticate with GCP
          command: |
            echo "$GCLOUD_SERVICE_KEY" > ${HOME}/gcloud-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
            gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - run:
          name: Set up SSH key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan "$GCP_VM_IP" >> ~/.ssh/known_hosts
      - run:
          name: Deploy to GCP VM
          command: |
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $GCP_VM_USER@$GCP_VM_IP \<< 'EOF'
              docker pull us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REPO/app:latest
              docker stop app || true && docker rm app || true
              docker run -d --name app -p 8080:8080 us-central1-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REPO/app:latest
            EOF
workflows:
  CICD:
    jobs:
      - continuous-integration
      - continuous-delivery:
          requires:
            - continuous-integration
