column_types:
  imbalance_data:
    id: category
    label: category
    tweet: category

  raw_data:
    "Unnamed: 0": category
    count: category
    hate_speech: category
    offensive_language: category
    neither: category
    class: category
    tweet: category

drop_columns:
  imbalance_data:
    - id
  raw_data:
    - "Unnamed: 0"
    - count
    - hate_speech
    - offensive_language
    - neither
