imbalance_data_columns:
  - id: category
  - label: category
  - tweet: category

raw_data_columns:
  - "Unnamed: 0": category
  - count: category
  - hate_speech: category
  - offensive_language: category
  - neither: category
  - class: category
  - tweet: category

drop_imbalance_data_columns:
  - id

drop_raw_data_columns:
  - "Unnamed: 0"
  - count
  - hate_speech
  - offensive_language
  - neither
