imbalance_data_columns:
  - id: category
  - label: category
  - tweet: category

raw_data_columns:
  - "Unnamed: 0": category
  - count: category
  - hate_speech: category
  - offensive_language: category
  - neither: category
  - class: category
  - tweet: category
#drop_columns:
#  - case_id
#  - yr_of_estab
