dataset_keys:
  imbalance_data: imbalance_data
  raw_data: raw_data

column_groups:
  imbalance_data:
    id: category
    label: category
    tweet: category

  raw_data:
    "Unnamed: 0": category
    count: category
    hate_speech: category
    offensive_language: category
    neither: category
    class: category
    tweet: category

targets:
  imbalance_data:
    - label
  raw_data:
    - class

drop_columns:
  imbalance_data:
    - id
  raw_data:
    - "Unnamed: 0"
    - count
    - hate_speech
    - offensive_language
    - neither
